Do not call project.getBuildDir() at shutdown.
It appears to lead to exceptions of the form:

java.lang.IllegalStateException: Cannot locate service of type
FileOperations, as ProjectScopeServices has been closed.

Test: PerformanceInfrastructureTest, no regression test yet.
Change-Id: I8dc8fafeff5ff91282e17a37073f5e7d12a9f204

Former-commit-id: 7609c717e84ac63dac372df55901923ac01126ef